### ISSUE TITLE
fluent api

### ISSUE THREAD

**Issue by dazinator** [libgit2/libgit2sharp#1033]
Libgit2sharp is fantastic.

I've started to have a go at creating a fluent api [over here](https://github.com/dazinator/FluentGit) - please have a quick look at the example code on the readme page for a quick intro to what it looks like so far. Would you ever consider adopting something like this directly into libgit2sharp? Or not interested? If you are I'll create a branch and do some initial work for review. If not, no worries :)

**Comment by nulltoken** [comment]
>Libgit2sharp is fantastic.

:heart: This is mainly because of all the amazing contributions (issues and pull requests) we've been lucky to receive.

>I've started to have a go at creating a fluent api over here - please have a quick look at the example code on the readme page for a quick intro to what it looks like so far.

Wow. This looks like a very neat initiative! Thanks for making the life of LibGit2Sharp users a bit easier from the code perspective :wink:

We're currently in the process of stabilizing the API and adding a new API layer at this point may be more confusing than helping.

I'd suggest to wait until the current API is stabilized (ie. when we release 1.0) and then revisit this subject with the other contributors.

**Comment by dazinator** [comment]
Cool beans - will close this for now then, and will raise an issue after 1.0 is released to see if anyone has a take on the idea. Meanwhile, I'll keep experimenting with fluentgit  to see what I can learn.
Cheers.
