### ISSUE TITLE
Malformed URL

### ISSUE THREAD

**Issue by leventesen** [libgit2/libgit2sharp#1045]
`Repository.Clone("http://pc2:60579/Gökçüoğlu.git", ".\\Git")` throws LibGit2Sharp.InvalidSpecificationException with message "Malformed URL 'http://pc2:60579/Gökçüoğlu.git'"

**Comment by ethomson** [comment]
You seem to have some invalid characters in your URL.  Please see [RFC2396](http://tools.ietf.org/html/rfc2396) for information on legal URLs.  Generally one would use a utility like [HttpUtility.UrlEncode](https://msdn.microsoft.com/en-us/library/system.web.httputility.urlencode%28v=vs.110%29.aspx) to encode characters that would otherwise be invalid.

**Comment by leventesen** [comment]
This code solved it
```cs
new Uri(gitUrl).AbsoluteUri
```
Thanks..
