### ISSUE TITLE
Weird calling conventions.

### ISSUE THREAD

**Issue by rdebath** [libgit2/libgit2sharp#1060]
I'm attempting to call `Repository.Network.Push` through DotNET interop. I've looked at the [example](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp.Tests/RemoteFixture.cs) and for the most part it seems reasonable but I can't assign a `LibGit2Sharp.UsernamePasswordCredentials` object to the `Credentials` property of the `LibGit2Sharp.PushOptions` object, it doesn't exist. 

There is a `CredentialsProvider` property but all it seems to do is throw a type error.

I assume you're using some feature of the `C#` compiler that's not strictly DotNET.

Can you give me some indication of the code that's actually being run here ?

Otherwise I suspect I'll end up creating a wrapper for your wrapper.

BTW: I've had a similar issue with the `Repository.ObjectDatabase.CreateCommit` method where the `parents` and `commentChar` arguments are weird types (Generic?); but I was able to work around that issue by using `System.Reflection.MethodInfo.Invoke` to wrap it on the fly.

**Comment by ethomson** [comment]
What do you mean by "DotNET interop"?  Is this COM?  Are you building a Primary Interop Assembly?

**Comment by ethomson** [comment]
Regardless, you will not be able to assign a `UsernamePasswordCredentials` to `PushOptions.Credentials`.  You would, I would expect, get some sort of type exception because those types aren't compatible...

[`CredentialsProvider`](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/PushOptions.cs#L13) is a [`CredentialsHandler`](https://github.com/libgit2/libgit2sharp/blob/b304c070de966c12a025a20208ee76d3026e2e08/LibGit2Sharp/Handlers.cs#L32), which is a delegate that provides the `Credentials`.

So you need to provide a callback here that will return the `UsernamePasswordCredentials`.  This is all .NET, nothing that's C# only.

**Comment by rdebath** [comment]
DotNET interop means calling the library routines from another language that isn't `C#` but is actually compiled to the "DotNET platform". 

The language in question is called "Microsoft C/AL".

**Comment by ethomson** [comment]
For what it's worth, ".NET Framework Interoperability" is a feature of C/AL.  To talk about "DotNET Interop" on a .NET project is not descriptive - we need to know *what* you're trying to interop with .NET.

There's nothing magical about delegates, this is part of .NET.  As I mentioned, it's not something specific to C# or F# or anything.  Your problem seems like a general C/AL to .NET interoperability problem, not something that's specific to LibGit2Sharp.  In general, you will need to either:

1. Pass a delegate from C/AL to .NET, or
2. As you indicated, create a wrapper on top of LibGit2Sharp to ease some of these concerns.

I really don't know if (1) is possible or not.  It's possible that (2) is a more convenient approach for you.  Sadly, I don't think that you'll find anybody here who is very familiar with C/AL.

I would recommend stackoverflow.com for both:

1. Questions about binding .NET libraries from C/AL, which I think will help you overcome the delegate problem (if, indeed, it is surmountable), and
2. General questions about LibGit2Sharp and how to use the API.  

All the LibGit2Sharp developers hang out on StackOverflow to answer API questions.  We just try to keep the issue tracker for bugs that need to be resolved.  Sadly, though, I'm not sure that we can help much with questions in the C/AL to .NET interop space.

**Comment by rdebath** [comment]
Okay, I was hoping "DotNET Interop" would be sufficiently clear to say that I'm using the library from a language that didn't grow up together with DotNET. 

Yes it is a limitation of C/AL, however, I very rarely run into delegates, generics or nullable types when interacting with DotNET libraries. To me this implies that it's not uncommon for them to be difficult to use from other languages (ie not C#)  and for this (or perhaps some other) reason it's a good idea to avoid them in a general DotNET (as opposed to C#) library.

If I'm wrong about this, no problem, I'll just go the wrapper routes; it'll give me a nice excuse to look into `System.CodeDom.Compiler`.

**Comment by ethomson** [comment]
It sounded to me like you were trying to deal with COM, which - quite honestly - might well be how C/AL is trying to interact.  (However, that would surprise me a little bit:  function pointers should get marshalled to .NET delegates over COM without too much problem.  But there may be some friction in the C/AL <-> COM side of things.)

I don't think that delegates, generics and the like should be difficult from any of the .NET languages...  We aim for a high degree of compatibility with the CLS, and I know that we've had people using .NET languages that aren't C# - I know that some of the contributors are F# hackers, and I know that somebody has used VB against LibGit2Sharp without pain.  Even PowerShell!

But for non-.NET languages, I would expect that understanding the surface area for what those languages support would be a language-by-language sort of thing.  And then the question becomes should our library be the lowest common denominator of - not .NET - but all the things that can talk to .NET?

**Comment by rdebath** [comment]
Nope, C/AL is definitely not COM now, it can't even talk to COM server side, remember Microsoft are hating COM nowadays. The C/AL actually runs as pure DotNET with Nav version 7&8, though I don't know if it's defined as a "DotNET language".

Nevertheless, it's ability to interoperate with C# is very limited; Classes (Methods, Properties, Enums, Constructors and "Events") and simple primitive types just about sums it up. It doesn't even implement the array convention, you have to use the methods (eg "item") that C# hides from the programmer. However, what it does implement seems to be enough (just barely) to use anything from the standard DotNET libraries you may want to. 

You might end up saying  ".NET languages, except C/AL" :smile:

**Comment by whoisj** [comment]
I'm not sure I'd say "Microsoft are hating COM nowadays". The entire C++/CX and WinRT platforms are built on top of COM (the `^` operator means COM). They seem fairly integral to the way Microsoft sees its future.

**Comment by rdebath** [comment]
You got me having a look around, I think yes, Microsoft are still hating on C++/COM see: https://msdn.microsoft.com/library/windows/desktop/dn614993.aspx which paraphrased seems to say "C++/COM is only any good for games."

But C++/CX is different, you see it's got an X in the name, that means it's good, see. 

It's also interesting that the "marshalling cost" between C-hash and C++/CX is being downplayed, and indeed seems to be smaller. I have always though it was really weird that it took so long to call a C++/COM function on the second call. Most (all?) other Jitted or Interpreted languages manage to make the second call as quick as anything else, after all everything is compiled to machine code in the end.

**Comment by nulltoken** [comment]
As this doesn't seem to be related to LibGit2Sharp, closing this now.

Cheers!
