### ISSUE TITLE
Error initializing task GenerateUniqueIdentifierTask when running build.libgit2sharp.sh against Mono 4.0.1

### ISSUE THREAD

**Issue by kjnilsson** [libgit2/libgit2sharp#1067]
I get the following issue when trying to build libgit2sharp on mono 4.0.1 / OSX

oryx:libgit2sharp karlnilsson$ ./build.libgit2sharp.sh
Mozilla Roots Importer - version 4.0.1.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Importing certificates into user store...
Import process completed.

Installing 'xunit.runners 1.9.2'.
Successfully installed 'xunit.runners 1.9.2'.
Installing 'LibGit2Sharp.NativeBinaries 1.0.51'.
Successfully installed 'LibGit2Sharp.NativeBinaries 1.0.51'.
Installing 'Moq 4.2.1409.1722'.
Installing 'xunit 1.9.2'.
Successfully installed 'Moq 4.2.1409.1722'.
Successfully installed 'xunit 1.9.2'.
Installing 'xunit.extensions 1.9.2'.
Successfully installed 'xunit.extensions 1.9.2'.
Installing 'xunit.runner.visualstudio 2.0.0-rc1-build1030'.
Successfully installed 'xunit.runner.visualstudio 2.0.0-rc1-build1030'.
XBuild Engine Version 12.0
Mono, Version 4.0.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 03/06/2015 10:19:38.
__________________________________________________
Project "/Users/karlnilsson/code/github/libgit2sharp/CI/build.msbuild" (Deploy target(s)):
	Target Clean:
		Commit SHA =
		Executing:  rm -r -f /Users/karlnilsson/code/github/libgit2sharp/CI/../Build
		Executing:  rm -r -f /Users/karlnilsson/code/github/libgit2sharp/CI/../LibGit2Sharp.Tests/bin/Release
	Target Init:
		Created directory "/Users/karlnilsson/code/github/libgit2sharp/CI/../Build"
	Target Build:
		ExtraDefine =
		Project "/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp.sln" (Build target(s)):
			Target ValidateSolutionConfiguration:
				Building solution configuration "Release|Any CPU".
			Target Build:
				Project "/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj" (default target(s)):
					Target PrepareForBuild:
						Configuration: Release Platform: AnyCPU
						Created directory "bin/Release/"
						Created directory "obj/Release/"
					Target CopyNonResxEmbeddedResources:
						Copying file from '/Users/karlnilsson/code/github/libgit2sharp/packages/LibGit2Sharp.NativeBinaries.1.0.51/libgit2/libgit2_hash.txt' to '/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/obj/Release/LibGit2Sharp.libgit2_hash.txt'
						Copying file from '/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/libgit2sharp_hash.txt' to '/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/obj/Release/LibGit2Sharp.libgit2sharp_hash.txt'
					Target GenerateSatelliteAssemblies:
					No input files were specified for target GenerateSatelliteAssemblies, skipping.
					Target GenerateUniqueIdentifierCs:
: error : Error initializing task GenerateUniqueIdentifierTask: The classes in the module cannot be loaded.
						Build FAILED.
						Errors:
						/Users/karlnilsson/code/github/libgit2sharp/CI/build.msbuild (Deploy) ->
						(Build target) ->
						/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp.sln (Build) ->
						(Build target) ->
						/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj (default targets) ->
						/Users/karlnilsson/code/github/libgit2sharp/LibGit2Sharp/UniqueIdentifier.targets (GenerateUniqueIdentifierCs target) ->
							: error : Error initializing task GenerateUniqueIdentifierTask: The classes in the module cannot be loaded.
							 0 Warning(s)
							 1 Error(s)

**Comment by nulltoken** [comment]
@kjnilsson Thanks for this report. Unfortunately, LibGit2Sharp isn't validated for Mono 4.0.x yet (which reminds me that we should update the Readme to state this).

This is related to an issue with XUnit (XUnit 1.9.2 doesn't work with Mono 4 and XUnit 2.0 doesn't work with Mono 3.6+. cf https://github.com/xunit/xunit/issues/158).

We still have to devise a plan regarding the support of Mono 4.0 (once we've validated that the XUnit issue is resolved)

/cc @Therzok @carlosmn @bording

**Comment by kjnilsson** [comment]
Thanks for the reply. From reading that xunit issue it appears there may be a fix in mono 4.0.2 (or whatever the next release will be). I shall wait for the next mono release and see. 

Cheers.

**Comment by sushihangover** [comment]
First:

I'm using libgit2sharp on OS-X using a 64-bit version of mono/llvm:
* 4.0.1 
* 4.0.2 
* 4.3.0 (Bleeding edge, repo HEAD)

All run fine, it also works with the std OS-X 32-bit 4.0.x distros from Xamarin.

Second, your 'bug':

On Mono (OS-X/Linux) The "GenerateUniqueIdentifierTask" error is caused by the custom build dll that is included in this projects repo (that was build on a Win-box...)

If you would actually compile that dll under mono as source is include in this project, you would see that there is a CS1701 warning generated. CS1701 should maybe really be an fatal ERROR.. 

The issue lays in that the Microsoft build tasks are not available in the later mono framework versions. And thus you would have to provide a custom runtime policy and a map file to jump through the hoops to make it work.

Third: 
* You can convert the CustomBuildTasks.dll to an exe and call it via a standard pre-build task and just nuke the three custom targets from the csproj file.
* Copy over the Microsoft.Build.Utilities.dll and Microsoft.Build.Framework.dll from the mono xbuild v12 build (NOT the dlls from a Window's box!) and a them to the repo.
* As an exe it is not loaded into xbuild (or mdtool) process and thus you avoid the framework mismatch and do not get a CS1701warning during compiling. 
* When run, mono will complain and warn you that there is a framework miss-match, but all is good (yep, that is the actual output below from my conversion):
```
mono ./CustomBuildTasks.exe 
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
```

Fourth:
* Don't change anything related to the targets and just update the one hash file and generate the other two as I do in a script that I bang'd out in a couple of minutes (see below). Once the csproj is updated via the script, you can also build it via mdtool or within Xamarin Studio or the plain-jane MonoDevelop.

IHMO: Using custom dll based targets are really going to bite you in the butt if you really plan on xplat development (vs just xplat deployment). And since all that is going on is generating a guid and grabbing the long/short git SHA a shell script and its PowerShell/cmd equal would be the cleanest xplat way. But again, just MHO.

kjnilsson, Have fun using this lib on OS-X.. I love it! (FYI: Using a 64-bit mono with llvm enabled, or pre AOTing everything once your program is done, you will see a 2-3x perf increase.

Assuming you can read a bash script, otherwise buyer beware ;-)
```
#!/bin/sh
read -d '' UniqueIdentifier <<- EOF
using System;

namespace LibGit2Sharp.Core
{
  internal static class UniqueId
  {
    public const String UniqueIdentifier = "GUIDHERE";
  }
}
EOF
#echo $UniqueIdentifier

read -d '' NativeDllName <<- EOF
using System;

namespace LibGit2Sharp.Core
{
    internal static class NativeDllName
    {
        public const string Name = "git2-GITSHASHORT";
    }
}
EOF
#echo $NativeDllName

guid=$(uuidgen)
gitshort=$(git log --pretty=format:'%h' -n 1)
gitlong=$(git rev-parse HEAD)

echo $gitlong > libgit2sharp_hash.txt
echo $UniqueIdentifier | sed 's/GUIDHERE/'$guid'/g' > Core/UniqueIdentifier.cs
echo $NativeDllName | sed 's/GITSHASHORT/'$gitshort'/g' > Core/NativeDllName.cs

read -d '' Targets <<- EOF
  <Import Project="UniqueIdentifier.targets" />
  <Import Project="NativeDllName.targets" />
  <Import Project="ExtraDefine.targets" />
EOF
cp LibGit2Sharp.csproj LibGit2Sharp.csproj.bak
cat LibGit2Sharp.csproj | grep -v "^\ \ <Import Project=\".*[r,e].targets\"\ />$" > LibGit2Sharp.csproj.new
if [[ -s LibGit2Sharp.csproj.new ]] ; then
cp  LibGit2Sharp.csproj.new LibGit2Sharp.csproj
echo "Run xbuild and have fun"
else
echo "Targets changed in file, csproj is being restore, regex needs reviewed"
cp LibGit2Sharp.csproj.bak LibGit2Sharp.csproj
fi
```

**Comment by Heather** [comment]
how do you deal with this bug?

**Comment by carlosmn** [comment]
This works with current versions of libgit2sharp and mono versions. We run CI with 3.12 and 4.3.
