### ISSUE TITLE
Publish Wizard with Visual Studio doesn't include native binaries of libgit2

### ISSUE THREAD

**Issue by cyril21** [libgit2/libgit2sharp#1126]
Related to : 
http://stackoverflow.com/questions/31113817/publish-wizard-with-visual-studio-doesnt-include-native-binaries-of-libgit2

The Publish Wizard to create a ClickOnce Application seems to not copy the `NativeBinaries` directory with `libgit2` .dll files x86 and amd64. 

After install a application on another computer than my dev environment I have this error :     
```
System.DllNotFoundException: Impossible de charger la DLL 'git2-e0902fb': Le   module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
   à LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   à LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   à LibGit2Sharp.Core.NativeMethods..cctor()
```

`LibGit2Sharp.dll.deploy` is correctly copied in the Application Files directory at the end of the publish process.

IDE : Visual Studio 2013 Express for Windows Desktop.

`LibGit2Sharp.0.21.0.176` is installed with NuGet.

Thanks.

**Comment by nulltoken** [comment]
Thanks for reporting this! 

However, I'm not sure we've got a ClickOnce wizard among the Core contributors. Could you please provide us with the steps we should follow in order to reproduce your issue?

**Comment by bording** [comment]
@nulltoken It's been a while, but I have used ClickOnce a few times, so I don't mind looking into this. I'm not sure if there is anything we can do to automatically include the NativeBinaries or not.

@cyril21 Do you by any chance have a choice of installers? ClickOnce might be built into Visual Studio, but it has a ton of problems. If you're looking for a ClickOnce-style application install, I'd recommend taking a look at **[Squirrel](https://github.com/Squirrel/Squirrel.Windows)** instead.

**Comment by bording** [comment]
@nulltoken Looking into this a bit, we could change the NativeBinaries.props file to add the files to the project as Content instead of None as it currently is. If we did this, then the Publish wizard will pick up the files and include them in the ClickOnce manifest.

The potential downside to this change is that by setting those files to Content, anyone using them with something that looks at the Build Action setting will start getting copies of those files where they normally wouldn't. For example the web publishing wizard/webdeploy stuff will include the NativeBinaries folder in the bin folder as usual, but there will be another copy sitting in the root of the publish folder.

@cyril21 Until we decide on making this change, you can manually add the files to the ClickOnce manifest, following the procedure described **[here](https://msdn.microsoft.com/en-us/library/6fehc36e(v=vs.120).aspx)**

I still think you'd be happier moving over to something like Squirrel instead though!

**Comment by nulltoken** [comment]
@bording Thanks a lot!

Could you please copy this above into a StackOverflow answer ? :wink:

**Comment by cyril21** [comment]
Ok, thanks all. 

@bording I will try with Squirrel.

**Comment by cyril21** [comment]
Everything works perfectly with Squirrel, just some times to understand the procedure.
It's much better than ClickOnce ! 

Problem solved for me.

**Comment by bording** [comment]
> Could you please copy this above into a StackOverflow answer

@nulltoken done!

**Comment by nulltoken** [comment]
...and upvoted!

**Comment by gaelj** [comment]
FYI, if anyone wants to do it with ClickOnce, you have to manually copy the correct DLL in your project folder, then in the file properties (those within visual studio) set build action to content.
Finally in thje project properties, publish, application files, you will now be able to include the DLL manually in the build. I tried on my x64 project with the x64 DLL and it works. Building for AnyCpu might be a little more tricky.
