### ISSUE TITLE
Repository.Clone() : Cross host redirect not allowed

### ISSUE THREAD

**Issue by john-grandy-opentable** [libgit2/libgit2sharp#1160]
Windows Server 2008 R2 SP2 
ASP.NET C# 
libgit2sharp 0.21.0.176 

From CLI this git operation succeeds without issue : 

`git clone https://www.github.com/{org-name}/{repo-name}.git` 

The expected local repo is created in folder `\{org-name}\{repo-name}` 

But when ASP.NET C# app attempts programmatically equivalent operation `LibGit2Sharp.Repository.Clone()` of same GitHub URI an exception is thrown : "Cross host redirect not allowed"

In the Visual Studio debugger I can see that the URI is being formed and passed to `Repository.Clone()` as expected -- so this isn't an issue with a malformed URI.

C# code : 

```
var cloneOptions = new CloneOptions { 
  BranchName = "master",
  Checkout = true,
  CredentialsProvider = (url, user, cred) =>    
  new UsernamePasswordCredentials { Username = {username}, Password = {password}}
};

string cloneResult;
try {
  cloneResult = Repository.Clone(
  "https://www.github.com/{my-org}/{my-repo}.git",
  "c:\github\{my-org}\{my-repo}",
  cloneOptions);            
} catch (LibGit2SharpException e) {}
```

`Repository.Clone()` throws a run-time exception : 

> Cross host redirect not allowed :       at
> LibGit2Sharp.Core.Ensure.HandleError(Int32 result)   at
> LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir,
> GitCloneOptions& opts)   at LibGit2Sharp.Repository.Clone(String
> sourceUrl, String workdirPath, CloneOptions options)

Apparently here is where `libgit2sharp` throws the exception on line 188 : https://github.com/libgit2/libgit2/blob/master/src/netops.c

**Comment by ethomson** [comment]
Can you sniff this with fiddler or wireshark?  Does the redirect header provide elucidation?  Off the top of my head:  GitHub is case insensitive when it comes to the org and repo URI, is it possible that you're not providing the canonical path (and you're being redirected to a URI with a different case)?

**Comment by john-grandy-opentable** [comment]
My logs show that the repo URI supplied to Repository.Clone() is identical ( including casing - entirely lower-case ) to the URI supplied to the manual CLI `git clone` on local server that successfully pulls-down the repo from GitHub.

You mention redirect header - what exactly would be performing a redirect ?

**Comment by carlosmn** [comment]
It's possible that the code is misinterpreting an absolute URL as a redirect to a different host. Did this repository recently get renamed?

**Comment by john-grandy-opentable** [comment]
I should have mentioned that the code works flawlessly on my local dev-test workstation ( Windows 8 ). In the Visual Studio debugger I can see that the URI is being formed and passed to Repository.Clone() as expected. And I can verify that the local repo is pulled-down as expected.  The `cross host redirect not allowed` exception only occurs on the remote server ( Windows Server 2008 R2 SP2 ).

Apparently here is where `libgit2sharp` throws the exception : https://github.com/libgit2/libgit2/blob/master/src/netops.c

**Comment by ethomson** [comment]
> You mention redirect header - what exactly would be performing a redirect ?

GitHub could give you a redirect for a plurality of reasons...  I couldn't enumerate all the scenarios without knowing more about their systems.

It's possible, of course, that there's just some dumb bug here, but I would like to rule out that this is behaving correctly first - you might actually be getting a cross-host redirect.  That's why it would be helpful to see the response itself.

**Comment by john-grandy-opentable** [comment]
When you say "response" are you referring to an http response received from an http request that `libgit2sharp` sends to GitHub ?  How would I retrieve the response body ?  It doesn't seem to be available as a property of the `LibGit2SharpException`

Actually I'm not clear on exactly what actions `Repository.Clone()` performs.  Does it identically perform the same git operations as `git clone` from the CLI ?

**Comment by john-grandy-opentable** [comment]
@nulltoken @ethomson any ideas on resolving this issue ?

**Comment by ethomson** [comment]
No, I'm afraid that I can't reproduce this, and I really do need to see some data from fiddler or wireshark in order to be of much help.  If you're able to capture that, it would be *very* helpful.

**Comment by john-grandy-opentable** [comment]
@ethomson using wireshark we've been attempting to analyze traffic.  we do see tcp ( not http ) traffic to github.com but it is encrypted. we only know it's github traffic because one of the headers contained unencrypted text "github.com"

please note that `cross-host redirect not allowed` exception appears to be machine-specific - because we don't encounter the exception in pipeline tests run on TeamCity build agents, plus we've run the test-suite on other developer workstations and not seen the exception.

**Comment by carlosmn** [comment]
GitHub canonicalizes its URLs as `https://github.com/{user}/{repo}(.git)`. You however keep using `https://www.github.com/` as a URL, which is a hostname which GitHub itself never produces, and it will redirect away from the `www` regardless of whether you claim to be a Git or a browser.

As such, it counts as a cross-host redirect, since `github.com` and `www.github.com` are not the same hostname. If you remove that extraneous `www.` prefix, it should work.

**Comment by john-grandy-opentable** [comment]
@carlosmn originally i was using `github.com` but switched to `www.github.com` in hopes of resolving this exception.  in any event, just now i revised my code from `www.github.com` to `github.com` but i still receive the `cross host redirect not allowed` exception.  this is expected because i'm finding that when i run my code on certain machines the exception is thrown, but not on others -- indicating perhaps that the underlying cause is environment-specific

**Comment by ethomson** [comment]
> @ethomson using wireshark we've been attempting to analyze traffic. we do see tcp ( not http ) traffic to github.com but it is encrypted. we only know it's github traffic because one of the headers contained unencrypted text "github.com"

You will need to look at the actual packets.  If you're cloning HTTPS, then use Fiddler, or Charles, and turn on its HTTPS decryption functionality.

I understand that this is environment specific, but it's quite specific to only your machine.  Nobody else has ever reported seeing this (erroneously).  I will wager a shiny new dollar that the machine that is seeing this problem is hitting some transparent proxy that is doing terrible things.  Perhaps a virus scanner or a malware scanner is installed?

**Comment by carlosmn** [comment]
Have you looked at the git configuration in those machines? It's possible that you have a url replacement configuration (`insteadof`).

**Comment by john-grandy-opentable** [comment]
`c:\users\{IIS AppPool name}\.gitconfig`  doesn't exist - which I find strange since I assume this is the account identity `libgit2sharp` assumes for its git operations ? 

Something just occurred to me : I believe my issues began around the time I installed Git Extensions -- do you know of any redirects GE might be performing ?

**Comment by john-grandy-opentable** [comment]
additional info : `curl --verbose "https://github.com/{org-name}/{repo-name}.git"` responds with `error 301 Moved Permanently Location: github.com/{org-name}/{repo-name}` which makes little sense because `curl --verbose "https://github.com/{org-name}/{repo-name}"` returns `404 Not Found` ... but please note this test produces identical responses on both the problem and the non-problem machines

**Comment by carlosmn** [comment]
Curl doesn't take the git URL rewriting configuration into account. We need to see what git and/or libgit2 are trying to connect to. You can export `GIT_TRACE=1` when running git in order to get more information if you don't want to worry with tracing the libgit2 conversation, but the curl output is not of much use.

**Comment by ethomson** [comment]
@john-grandy-opentable I trust that things worked out in the end - I'm closing this, it's quite stale now.
