### ISSUE TITLE
Which commits are being pushed

### ISSUE THREAD

**Issue by gabriel175** [libgit2/libgit2sharp#1161]
Hi all,

We want to start using libgit2sharp in our app. We allow pushing to remote, but before the push operation we would like to show which commits are going to be pushed (it means - which new commits have been done since the last push operation).

I checked the docs and over the web and it seems that the only way of doing it is “remembering” the last date-time of the last push operation and then retrieving all the commits from the commit tree since that date.

Is there any easier way to do so?

Thanks a lot

**Comment by Therzok** [comment]
Yeah, use the CommitLog and Take commits while they exist in the current branch, and do not exist in the remote tracked branch.

**Comment by shiftkey** [comment]
@gabriel175 if you have tracking setup for the branch, you could leverage that here...

**Comment by gabriel175** [comment]
Thanks for the answer.
 @Therzok your suggested approach can be problematic since i might end up iterating the collections many times before i find the required commits.

@shiftkey i think i didn't understand your comment, what do you mean by tracking setup for the branch?

Thanks again :)

**Comment by sitereactor** [comment]
@gabriel175 I've recently done something similar. As mentioned above it should be fairly straight forward when you have tracking on your branch. Ie. your master branch has a remote origin that you use for Push and Fetch. Using libgit2sharp you can see it doing something like this (given you are on the master branch)

```
using (var repo = new Repository("C.\path\to\repository"))
{
    var trackingBranch = repo.Head.TrackedBranch;
}
```

Then you can take the `Id` of the `Tip` of the `Head` and compare it to that of the tracking branch like so:

```
using (var repo = new Repository("C.\path\to\repository"))
{
    var trackingBranch = repo.Head.TrackedBranch;
    var log = repo.Commits.QueryBy(new CommitFilter 
                { Since = repo.Head.Tip.Id, Until = trackingBranch.Tip.Id });

    var count = log.Count();//Counts the number of log entries

    //iterate the commits that represent the difference between your last 
    //push to the remote branch and latest commits
    foreach (var commit in log)
    {
        Console.WriteLine(commit.Message);
    }
}
```
I have only explored the `CommitFilter` thus far, so there might be a better/faster way of doing this (I'm still learning :wink:).

Please note though, that based on your starting point you might need to configure the remote tracking branch and fetch in order to do the comparison (before pushing).
Maybe this example will be useful to you in terms of setting the remote on your local/source repository (master branch):
```
private void EnsureRemoteOrigin(string sourceRepositoryPath, string destinationRepositoryUrl)
{
    using (var repository = new Repository(sourceRepositoryPath))
    {
        if (repository.Network.Remotes.Any(x => x.Name.Equals("origin")) == false)
        {
            var remote = repository.Network.Remotes.Add("origin", 
                destinationRepositoryUrl, "+refs/heads/*:refs/remotes/origin/*");
        }

        var masterBranch = repository.Branches["master"];
        if (masterBranch != null && masterBranch.IsTracking == false)
        {
            var updatedBranch = repository.Branches.Update(masterBranch, 
                b => b.Remote = "origin",
                b => b.UpstreamBranch = "refs/heads/master");
        }
    }
}
```

Hope this helps

**Comment by gabriel175** [comment]
@sitereactor  Thank you very much, it was excatly what i needed :)
