### ISSUE TITLE
Working with remote - authentication + create remote repository

### ISSUE THREAD

**Issue by gabriel175** [libgit2/libgit2sharp#1162]
Hi,

We are adding a functionality of working with remote Git repositories.
During the development process we faced 2 main issues :

1. When user tries to connect to remote (for push/pull operation) there is no way of authenticating the credentials that he entered except of making the push/pull operation and wait for failure. Is there anyway that we can verify before the operations that the credentials are valid?

2. When user works with local repository and wants to publish the repo to a remote, is there a way of creating a new repository on a remote? (we found only a functionality of working with existing remote repository).

If those functionalities are missing, are they planned for future versions of libgit2sharp?

Thanks a lot.

**Comment by ethomson** [comment]
> When user tries to connect to remote (for push/pull operation) there is no way of authenticating the credentials that he entered except of making the push/pull operation and wait for failure. Is there anyway that we can verify before the operations that the credentials are valid?

Well, you have to make *some* HTTP request or some SSH command to know whether it failed.  And since authentication could be done on a repository-by-repository basis, you really need to hit some git endpoint with credentials to know whether they're accepted for that repository.  So really, hitting the `/info/refs` is the first opportunity you have to validate your credentials.

> When user works with local repository and wants to publish the repo to a remote, is there a way of creating a new repository on a remote? (we found only a functionality of working with existing remote repository).

No.  This is not a part of the Git protocol.  Some hosting providers may provide some functionality to do this.  If you're using GitHub, see [Octokit.net](http://octokit.github.io/).  If you're using Visual Studio Online, see [Infinity.net](https://github.com/ethomson/infinity.net).  Otherwise, you may wish to ask your hosting provider.

**Comment by gabriel175** [comment]
Thanks a lot! @ethomson
