### ISSUE TITLE
Files reported as modified but are binary equal

### ISSUE THREAD

**Issue by jamesfoster** [libgit2/libgit2sharp#1244]
I'm having an issue with `Repository.RetrieveStatus()`. It is reporting several files as modified when they are binary equal to what is committed.

There are no local changes.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

Auto CRLF is set to false. (It is globally set to `true` but locally it's set to `false`)

```
$ git config --local -l
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
core.autocrlf=false
```

There is no `.gitattributes` file.

I'm using LibGit2Sharp 0.21.0.176. The following code shows several files as modified.

```
var repo = new Repository(path);

var files =
    from f in repo.RetrieveStatus()
    where f.State != FileStatus.Ignored &&
          f.State != FileStatus.Untracked
    select f;

foreach (var file in files)
{
    Console.WriteLine($"{file.State}\t{file.FilePath}");
}
```

Why is `RetrieveStatus()` reporting modifications when `git status` does not?

Let me know if there's anything I can do to get you any other information you need to help diagnose the problem.

James

**Comment by ethomson** [comment]
>  It is reporting several files as modified when they are binary equal to what is committed.

How have you determined that they are binary equal?  Are you comparing `git hash-file` to `git ls-files`?  Can you provide the output?

What version of Git for Windows are you using?

**Comment by jamesfoster** [comment]
Thanks, after looking at the hash they are different. I used `git show` to grab a file and there are line ending differences.

Not sure how this happened since I've got autocrlf turned off. I've deleted my entire working tree and done a full checkout but there are still line ending changes. Is there any way to do a checkout so that I end up with exactly the same bytes on disk as in the repo?

Having said that, shouldn't git and libgit2 report the same differences? If I had autocrlf turned ON, libgit2 would report every file as modified *all of the time*. There is no situation where that would be useful.

Is there another method I can call, other than `RetrieveStatus`, that will return the same statuses as git?

**Comment by ethomson** [comment]
You mentioned that `core.autocrlf` was set to false in your *local repository*, but true globally.  Presumably that means that there was a point in time where `core.autocrlf` was *not* set to false?  Perhaps after the initial clone (before you set `core.autocrlf`)?

> Not sure how this happened since I've got autocrlf turned off. I've deleted my entire working tree and done a full checkout but there are still line ending changes.

Can you walk me through what you did here?  Did you use git or LibGit2Sharp to do the checkout?  What does the file look like in the repository?  In your working directory?

> Having said that, shouldn't git and libgit2 report the same differences?

Yes.  I suspect that you're using a newer version of git (2.x?) which generously started putting more precise timestamps into the index, which confused libgit2, so it will rescan your files.  I suspect that if you `touch` all the files in your working directory that `git status` will report identical results.  This is fixed in newer versions of libgit2, so the next LibGit2Sharp should correct this.

**Comment by ZxoR** [comment]
I've also affected by this bug.

**Comment by whoisj** [comment]
`autocrlf` is pure evil. I highly recommend disabling it all together, everywhere and rely on `.gitattributes` solely. If your workplace or development team don't follow, explain to them the error of their ways until they do. :wink: 

That said, @ethomson is likely correct that you were bitten by `autocrlf` during the initial clone. Though, since `.gitattributes` is a priority file I am surprised.

**Comment by ethomson** [comment]
LibGit2Sharp v0.22 has been released, which includes compatibility with Git 2.x (which uses nanosecond timestamp resolution).  This confused us, and we ended up more aggressively examining the working tree for changes, which would show mismatches between configured line endings and the actual files in the repository as changes.  This should now be resolved.
