### ISSUE TITLE
How to connect VSO without cleartext UserName and Password like OAuth

### ISSUE THREAD

**Issue by v-tapate** [libgit2/libgit2sharp#1246]
Hello,

I tried to connect VSO using DefaultCredentials. but it is throwing error for authentication. I have to use UsernamePasswordCredentials with clear text userName and Password which is not good. VSO has facility for OAuth and Personal Access Token. Could you please help me out if OAuth is in place in LibGit2Sharp or Personal Access Token.

Thanks & Regards,
Tarun Patel

**Comment by ethomson** [comment]
`DefaultCredentials` is SPNEGO (Kerberos, or NTLM) aka "single sign-on".  You cannot use this with Visual Studio Team Services, since none of these mechanisms are supported.

If you need a Personal Access Token, you need to specify it with the username and password fields.  Since this is protected by HTTPS, this is *not* sent in the plain text.

**Comment by ethomson** [comment]
We reserve the bug tracker for bugs, not how-to questions.  If you have further questions about how to enable this, please ask on [stackoverflow](stackoverflow.com) where we'd be happy to work with you.
