### ISSUE TITLE
Specify a timeout for the fetch operation.

### ISSUE THREAD

**Issue by rovinbhandari** [libgit2/libgit2sharp#1253]
Hi

I'm using libgit2sharp to automatically update a local repository (~8GB in size) using "fetch". Fetch gets triggered every 20ish minutes; however, I see that intermittently, the fetch operation hangs indefinitely. I've seen fetch hang as much as 2 days sometimes.

1. Is there a way to get some information about what is hanging under the hood, other than running it under debugger and hoping that it would hang?
2. I couldn't find a way to specify a timeout for the fetch operation; is it possible? If not, does it qualify as a valid feature request?

Thanks!

**Comment by Aimeast** [comment]
Because `timeout comes from WinHttpReceiveResponse(); MSDN suggests that the default value for this is 30 seconds, which is regrettably low.` see http://stackoverflow.com/a/21603417/1011174

libgit2 has prepared the argument for set timeout, but not yet introduce into libgit2sharp. see https://github.com/libgit2/libgit2/pull/2502.

**Comment by rovinbhandari** [comment]
To clarify, my issue is that fetch hangs indefinitely, and not that fetch fails too early, which seems to be the gist of what @Aimeast said above. Correct me if I interpreted it wrong.

**Comment by carlosmn** [comment]
We do not timeout when fetching since the server can take an arbitrary amount of time to prepare the packfile and send the data. In libgit2 you can cancel a fetch, but if we're blocking trying to receive the data, that won't really help.

We do want to add cancellation token support, but we need to make sure it works across the different languages, so it'll take a while to build correctly.

**Comment by carlosmn** [comment]
This is tracked in libgit2/libgit2#3334

**Comment by Piedone** [comment]
The ability to set a timeout appears to be possible in libgit2 as per https://github.com/libgit2/libgit2/pull/2502. Am I correct that this option is not surfaced in libgit2sharp as of today? Not talking about a generic approach to handle cancellations.

**Comment by carlosmn** [comment]
As the discussion in the PR shows, it's not about setting the timeouts, but removing them. Being able to timeout a fetch _is_ a generic cancellation.

**Comment by Piedone** [comment]
OK, thanks.
