### ISSUE TITLE
Test failure: NoPublicTypesUnderLibGit2SharpCoreNamespace

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#1312]
This test fails in the master branch (as of 1fb7fc5b1d26c893e085c2782d5ee483d56c5a18)

```
Test Name:	LibGit2Sharp.Tests.MetaFixture.NoPublicTypesUnderLibGit2SharpCoreNamespace
Test FullName:	LibGit2Sharp.Tests.MetaFixture.NoPublicTypesUnderLibGit2SharpCoreNamespace
Test Source:	C:\Users\andarno\git\libgit2sharp\LibGit2Sharp.Tests\MetaFixture.cs : line 298
Test Outcome:	Failed
Test Duration:	0:00:00.003

Result StackTrace:	at LibGit2Sharp.Tests.MetaFixture.NoPublicTypesUnderLibGit2SharpCoreNamespace() in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp.Tests\MetaFixture.cs:line 324
Result Message:	Public type 'LibGit2Sharp.Core.LeaksContainer' under the 'LibGit2Sharp.Core' namespace.
```

**Comment by carlosmn** [comment]
This happens because the compilation defines `LEAKS_IDENTIFYING` which makes us create this flag, but the tests got compiled by VS itself which did not, thus not making us include `LeaksContainer` in the list of classes that are OK to export.

We should probably get rid of this long-term as we'd actually want to expose things in core.

**Comment by carlosmn** [comment]
Does #1317 fix it for you?

**Comment by ethomson** [comment]
I think #1317 should fix this - @AArnott please feel free to reopen if it doesn't.
