### ISSUE TITLE
Roadmap \ Next Release

### ISSUE THREAD

**Issue by mikefourie** [libgit2/libgit2sharp#1432]
Hi

Do you have a roadmap anywhere for this project. Also, any ideas on the next release date. We are using fixes in the 'unofficial' 0.24 and a release would be handy for various reasons.

Regards

Mike

**Comment by ethomson** [comment]
Hey @mikefourie - great question and I wish that I had a better answer.

We're sort of cruising without a maintainer at the moment.  I guess I'm the de facto maintainer, but I'm stretched a bit thin already so I'm not able to really give LibGit2Sharp the love that it deserves.

I think that the major thing in the works is the portable library version (https://github.com/libgit2/libgit2sharp/pull/1318).  Since this work is really heavy duty refactoring, I have been reluctant to make too many other major changes to avoid megaconflicts.

Once this is merged, I think that we will be in good shape to make a release...

Sorry about the delays.

**Comment by pdrhsm** [comment]
@ethomson the portable version seems to be completed as of 9 days ago 👍  Any eta on when to release it?

**Comment by ethomson** [comment]
This was merged at the very beginning of this release cycle to let things get nice and stable before making a proper point release with it.  We'll do the first prerelease soon; there are some changes that need to be made to our prerelease build process.

**Comment by ethomson** [comment]
We released v0.24, I'm going to close this now.
