### ISSUE TITLE
Date pushed is the date I run the program

### ISSUE THREAD

**Issue by FurkanS1821** [libgit2/libgit2sharp#1434]
I use this library in a discord bot, which pushes commit regularly, I realized something. The date of latest commit is always when I first run the bot, not when I push the changes. I hope you fix it soon.

P.S. I clone the repo on initialization.
P.S. 2: I do staging and committing right before pushing them, not weeks ago.

**Comment by norek** [comment]
Hi, can you share some code? How you get date of commit?
Can you write some tests and get this bug?

**Comment by FurkanS1821** [comment]
```cs
var signature = new Signature("FurkanS1821", "myEmailAddress", DateTimeOffset.Now)
var repo = new Repository("Repository/Path");
Commands.Stage(repo, "File1/path");
Commands.Stage(repo, "file2/path");
repo.Commit("CommitName", signature, signature);
var options = new PushOptions
{
    CredentialsProvider = FunctionGettingMyCredentials
};
repo.Network.Push(repo.Branches["master"], options);
```
I use this code.

**Comment by carlosmn** [comment]
If you're the one providing the signature, then it's something within your code that is setting the date to be old. Pushing has no effect on the commit dates, so yo should be able to check what dates you're passing in for each commit and verify whether you're caching something there. Can you share some specifics on what dates or how you're storing them?

**Comment by whoisj** [comment]
Sounds like a fundamental misunderstanding of what a commit date means.

Since the dates associated with commits are part of the data blob used when generating the identity of the commit, they cannot be changed without altering the commit's identity. Therefore, the dates are set before the commit is given an identity and therefore before any references can refer to it.

Pushing a commit to another repo copies the commit, intact and unaltered, to the foreign repository. The commit retains its original identity (if it did not, how would it possible to understand the union, intersections, or compliment of two repositories?).

This means pushing a commit will never affect the author nor committer dates of the commit.

**Comment by FurkanS1821** [comment]
Fixed the issue by using `DateTime.Now` instead of `DateTimeOffset.Now`. Sorry for bothering your time.

**Comment by whoisj** [comment]
> Fixed the issue by using DateTime.Now instead of DateTimeOffset.Now. Sorry for bothering your time.

Wait what? `DateTimeOffset` has an `implicit operator DateTime(DateTimeOffset)`, there should have been no issue there. @FurkanS1821 if that simple change then there is a bug somewhere. Your code, libgit2sharp, libgitw, and/or netfx (listed in order of most to least likely).

**Comment by FurkanS1821** [comment]
Well, it sounded weird to me, but somehow, using `DateTime.Now` worked. I realized this when using `DateTimeOffset` in message dates caused the time to be the time I run the program.
