### ISSUE TITLE
12 Dll copied to output even if using .NET 4.7.1

### ISSUE THREAD

**Issue by Rowandish** [libgit2/libgit2sharp#1593]
I'm wondering why LibGit2Sharp copied to output path 12 dll, even if .NET is 4.7.1.

### Reproduction steps

Create a new project, add `libgit2sharp` as nuget package, set .NET Framework to 4.7.1 and buid.

### Expected behavior

Only LibGit2Sharp.dll (or few dependencies) copied to output

### Actual behavior

12 extra dll are copied:

- `System.Data.Common.dll`
- `System.Diagnostics.StackTrace.dll`
- `System.Diagnostics.Tracing.dll`
- `System.Globalization.Extensions.dll`
- `System.IO.Compression.dll`
- `System.Net.Http.dll`
- `System.Net.Sockets.dll`
- `System.Runtime.Serialization.Primitives.dll`
- `System.Security.Cryptography.Algorithms.dll`
- `System.Security.SecureString.dll`
- `System.Threading.Overlapped.dll`
- `System.Xml.XPath.XDocument.dll`

### Version of LibGit2Sharp (release number or SHA1)

0.25.2

### Operating system(s) tested; .NET runtime tested

Windows 10, .NET 4.7.1

It is a standard behaviour? It is possibile to avoid such dll?

**Comment by bording** [comment]
Those additional assemblies are expected. LibGit2Sharp is a .NET Standard 2.0 assembly, so that means that depending on the version of the .NET Framework you're using, you'll see additional support assemblies in your bin folder. If you look at the content of those assemblies, most of them contain no actual implementation code, and just have `TypeForwardedTo` attributes to forward over to the real types contained in the framework.

If you were to target the lowest version of the framework that supports the standard, 4.6.1, you'd see that there are a lot more of those additional assemblies.

However, if you instead target 4.7.2, you'll see that there are no additional assemblies at all, as you were expecting.

**Comment by Rowandish** [comment]
Ok, it works ! Thanks 👍
