### ISSUE TITLE
Support for building on FreeBSD

### ISSUE THREAD

**Issue by jasonpugsley** [libgit2/libgit2sharp#1695]
This is a feature request to support LibGit2Sharp on FreeBSD

Hi, I'm looking for some guidance on what it would take to add FreeBSD to the
list of supported platforms. I'm currently using FreeBSD 12 and I can see libgit2
exists in the FreeBSD ports, installed as
/usr/local/lib/libgit2.so.0.28.1

FreeBSD in the world of .NET is still a work in progress and will not be an
officially supported OS on .Net Core 3.0, however LibGit2Sharp is used in the
dotnet source build system so building parts of .NET Core on FreeBSD has a
dependency on this. The current workaround is to build those parts on
Windows but other apps will still want to use LibGit2Sharp.

As of .NET Core 3.0 Preview 6, FreeBSD is now a listed property of the [OSPlatform](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.osplatform?view=netcore-3.0) class.
It's used to select the current OS in LibGit2Sharp/Core/Platform.cs
So this would need to be added:
```c#
if (RuntimeInformation.IsOSPlatform(OSPlatform.FreeBSD))
{
    return OperatingSystemType.Unix;
}
```

This is as far as I've researched the task for this repo and I need to take a
look at LibGit2Sharp.NativeBinaries as well, but I would appreciate any
pointers you can give me on areas of the code that need modifying for
this effort.

Thanks,
Jason

OS Version: FreeBSD 12
RID: freebsd-x64
TargetFramework: netcoreapp3.0 (Preview 6 or later)

root@freebsd:/usr/share/dotnet # dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     FreeBSD
 OS Version:  12
 OS Platform: FreeBSD
 RID:         freebsd.12-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  3.0.100-preview6-012264 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by bording** [comment]
I wouldn't expect there to need to be any changes to the code here. The primary thing you'd need is a native binary built against the FreeBSD dependencies. 

A prerequisite for adding something like this is that the appropriate RIDs have to exist in the runtime.json file of the version of .NET Core you want to run against. It looks like these have been added, at least in the master branch of the corefx repo, so it seems like that prereq has been met.

The stance I've taken in the past is that we'd only consider adding another binary to the increasingly large LibGit2Sharp.NativeBinaries package for officially supported operating systems, so it doesn't seem like FreeBSD is one we'd consider right now.

You mentioned the reason you're looking into this is because building .NET Core requires it. The only place I'm aware of where that is true is the Source Link packages. Is there somewhere else?

The reason I'm asking is that the Source Link packages have dropped the LibGit2Sharp dependency in the last couple of betas and have gone with a fully managed implementation instead, specifically because LibGit2Sharp is always going to lag behind in its support for operating systems.

We aren't likely to support FreeBSD as long as Microsoft doesn't consider it a supported OS, but the good news is that it likely doesn't matter for your scenario.

**Comment by jasonpugsley** [comment]
OK, thanks for the response. I understand your position and I'll close this issue. I will keep
looking at this myself and hopefully when the time comes I'll have a PR to submit when
FreeBSD joins the .NET Core family.

Admittedly my understanding of versions and dependencies in the dotnet source is still
a work in progress but LibGit2Sharp is referenced in several places in the build source
including CLI, CoreCLR and Arcade.

Thanks again,
Jason

**Comment by bording** [comment]
> Admittedly my understanding of versions and dependencies in the dotnet source is still
a work in progress but LibGit2Sharp is referenced in several places in the build source
including CLI, CoreCLR and Arcade.

Can you point me at some specific examples of this?
