### ISSUE TITLE
Ignore Mutant streteragy

### ISSUE THREAD

**Issue by maulikhdave9601672767** [libgit2/libgit2sharp#1802]
I have legacy system with 10000 test cases its take 3 to 4 hours lets assume
now after 1 time i run strker i got plenty bugs i resolved.
but for next run i want to ignore all the mutant which are already passed in first run .
so lets take  example:
in first run i have not got any issue related  "String Literal" 
so for second run for my all test i dont want to use it 
please suggest 
so when mutan run second time it automatically ignore passed mutant

**Comment by Stijn-Rutten** [comment]
Hey @maulikhdave9601672767 

First of all, this is not an issue you should post to libgit2sharp since this is a question about stryker. In case you're talking about stryker-net, we are currently working on a feature over [here](https://github.com/stryker-mutator/stryker-net/labels/Feat%3A%20Dashboard%20Compare) that uses results from the previous run for unchanged mutants. For further questions about this, please move this issue over to stryker-net.

**Comment by bording** [comment]
@Stijn-Rutten Thanks for commenting.

Since this clearly has nothing to do with LibGit2Sharp, I'm going to go ahead and close the issue.
