### ISSUE TITLE
About RepositoryNotFoundException

### ISSUE THREAD

**Issue by No54** [libgit2/libgit2sharp#1808]
Hi, I met a problem as follow, 
LibGit2Sharp.RepositoryNotFoundException: Path 'E:\testPath\' doesn't point at a valid Git repository or workdir.

I am sure that the path has a ".git" folder and it pull, push, sync... well. 

And, I try to search this exception, but no useful content been found.

Would you please show me some more infos? 

Thank you!    ๑乛◡乛๑

**Comment by No54** [comment]
here's my code, the exception came out from the line 1. 

`                var repo = new Repository(inEntity.Path);
                LibGit2Sharp.PullOptions options = new LibGit2Sharp.PullOptions();
                options.FetchOptions = new FetchOptions();
                options.FetchOptions.CredentialsProvider = new CredentialsHandler(
                    (url, usernameFromUrl, types) =>
                        new UsernamePasswordCredentials()
                        {
                            Username = "user",
                            Password = "pass"
                        });
                Signature author = new Signature("user",
                    "mail", DateTime.Now);
                LibGit2Sharp.Commands.Pull(repo, author, options);`

**Comment by No54** [comment]
i got it. IIS must be permitted to access the path

**Comment by karoly-ozsvart-betsson** [comment]
If you have the same exception, first verify that the path **really** is a valid git repository by running a git command from inside the directory, e.g. `git fetch`.

(In my case the problem was that a previous clone operation got interrupted and it resulted an invalid git repository. It had some content, and the `.git` folder too, but it was incomplete.)
