### ISSUE TITLE
Unable to load shared library 'git2-572e4d8' or one of its dependencies

### ISSUE THREAD

**Issue by p-brito** [libgit2/libgit2sharp#1899]
I built a service to clone a specific repo but, it works only when I run it locally, if I deploy this service to Amazon ECS it throws the following exception.

System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-ef5a385' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-ef5a385: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---

Docker
Build -> FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build 
Runtime ->FROM mcr.microsoft.com/dotnet/runtime:5.0

Publish service using ->  dotnet publish ./${file%.*}/$file -c Release -r rhel-x64 -o /app

How can I solve this?

**Comment by bording** [comment]
That error means that you're likely not bundling the correct native libgit2 binary for the specific distro that you're trying to run on.

That would be controlled by the RID passed to the `-r` parameter.

What version of LibGit2Sharp are you using? I'd recommend giving the latest prerelease a try. It has simplified the native dependencies so there's less change of a RID mismatch.

**Comment by p-brito** [comment]
Hi @bording, first of all, thank you for replying so quickly.

The version that I'm using is the latest prerelease, v0.27.0-preview-0102. 
Do I have to install the LibGit2Sharp.NativeBinaries?
Maybe this is not compatible with "rhel-x64" what do you think?

**Comment by bording** [comment]
> The version that I'm using is the latest prerelease, v0.27.0-preview-0102

I don't think that can be true. The error message you posted shows that it's failing because it can't find `git2-ef5a385`, but v0.27.0-preview-0102 would be looking for `git2-6777db8`.

> Do I have to install the LibGit2Sharp.NativeBinaries?

You don't have to reference it directly, the correct native binaries package gets brought in transitively based on the version of LibGit2Sharp you are referencing.

> Maybe this is not compatible with "rhel-x64" what do you think?

Why are you referencing that specific RID? It looks like you are using the Microsoft Docker images, and they are based on Debian, Alpine, or Ubuntu (based on which specific tag you reference).

A general good practice (and with the latest prerelease version you can follow it) is that you should only reference the general "os-platform" RIDs, so in your case if you're looking for a platform-specific deployment, you'd used `linux-x64`.

**Comment by danielgarner64** [comment]
If you aren't worried about using older versions and just want everything to work straight out of nuget.
The solution is use the previous version of LibGit2Sharp.native binaries (2.0.306).
And the newest version of libgit2sharp (0.26.2)
And then docker images, this is the only .net5 I know will work with this package:
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.12 AS base

**Comment by bording** [comment]
@danielgarner64 That is terrible advice. You should always use the version of the native binaries package that the main package lists as the dependency.

**Comment by p-brito** [comment]
@bording  Sry for the delay, the problem was solved by updating the package to the latest pre-release. Ty for your help.

**Comment by bording** [comment]
@p-brito Glad to hear you got it working!
