### ISSUE TITLE
Correct usage of the using statement should be documented

### ISSUE THREAD

**Issue by yysun** [libgit2/libgit2sharp#28]
Hi,

I have an example listed below. Can you see any problem from it?

```
    public IEnumerable<string> GetRefs()
    {
        var tempFolder = ".....";

        using (var repository = new LibGit2Sharp.Repository(tempFolder))
        {
            return from r in repository.Refs
                       select r.CanonicalName;
        }
    }

    [TestMethod()]
    public void GetRefsTest()
    {
        var refs = GetRefs();
        foreach (var r in refs)
        {
            Console.WriteLine(r);
        }
    }
```

The test method GetRefsTest will throw exception: System.ObjectDisposedException: Safe handle has been closed.

Regards,

yysun

**Comment by john-grandy-opentable** [comment]
`Write your code in a way that you have a reference to the repository object at a higher scope. A     Repository object is meant to be instantiated and held onto; it is the root aggregate object for the entire API. All enumerable methods on the Repository will require access to the repository so you can't Dispose it and then later expect to access it.`

But isn't this at odds with the best practice of keeping `using()` statements as short as possible ?

Also: within a single method any problem with instantiating a Repository object twice ?  so something like this : 

    var repo = new Repository({local-path}, RepositoryOptions);
    using(repo) {
    // some stuff
    }
    // some other stuff
    var repo = new Repository({local-path}, RepositoryOptions);
    using(repo) {
    // even more stuff
    }

**Comment by Therzok** [comment]
@john-grandy-opentable I don't see that as a problem, but some stuff gets smart-cached, so reusing is useful. Why waste resources (reloading) when caching (of pack-files for example) comes into place?

That's the best practice of `using`, but not all IDisposable go through `using`. Long-lived objects can just get disposed whenever the whole thing ended.

Actually creating a new repository for _every_ action can be a _slow_ operation.

**Comment by john-grandy-opentable** [comment]
#Therzok would you say best practice for `using(Repository)` is once per method ?  or would you say a elevated scope ( e.g. class-level ) is a better practice ?

Because I was receiving `Access Denied` errors on `.git\index`and `.git\index.lock` I became concerned I wasn't releasing resources.  So I moved away from a single global `Repository` instance and attempted to isolate usage of `Repository` to the narrowest ranges possible - which in many cases meant multiple `using()` statements per method.  But now I'm getting run-time exceptions `safe handle has been closed` which indicates resources are not available even though I've re-instantiated the `Repository` object.

**Comment by Therzok** [comment]
@john-grandy-opentable Why would you want to _delete_ .git folders right after usage? (Marking the items as `FileAttributes.Normal` does indeed help with that though, .git folders are special in their own way). You also cannot delete while a repository is in use, obviously.

You're getting safe handle errors due to reasons mentioned above. Lazy evaluations stay lazy until evaluated. You need to force eager evaluation by doing a `ToList` or `ToArray` call.

**Comment by john-grandy-opentable** [comment]
@Therzok ah sorry let me explain better. 

Errors attempting to delete files in `\.git` folder is a separate problem ( this is my desperation clean-up code that deletes the git local repo dir and re-clones ).  

As explained in my original issue description, my current problem is that I receive Access Denied errors on attempting the libgit2sharp programmatic equivalent of git operations such as `git clean` and `git checkout master`.  

My theory is that this is due to dangling Repository objects that were not cleaned-up properly. There I refactored my code to effect more granular usage of `Repository` object via `using() {}` statement blocks.  

However, this in turn led to a new exception `safe handle has been closed` which seems to imply that creating/using/disposing a `Repository` object does not completely free its resources -- at least not in the scope of the current method -- because if later in same method I fresh instantiate another `Repository` object in that method, when I execute its operations I get `safe handle has been closed`.

**Comment by nulltoken** [comment]
The `safe handle has been closed` could be thrown in the following context:

```csharp

Commit commit = null;

using (var repo1 = new Repository("...")
{
    commit = repo1.Head.Tip;
}

// Other unrelated things

// ....

using (var repo2 = new Repository("...")
{
    // Use the `commit` variable created above
}

Each object returned by LibGit2Sharp is tied to a `Repository` and cannot safely be used outside of its initial scope.

**Comment by ImaBrokeDude** [comment]
If I am looking at that properly yeah, that could be correct because Commit might be a reference type and not a Value type.
