### ISSUE TITLE
(Slow??) Speed checkout

### ISSUE THREAD

**Issue by reisi007** [libgit2/libgit2sharp#623]
Hi :)
I am not sure, whether it is slow, but I guess it needs ~half the time with git...
Why am i complaining? I made a small tool, using your Libary (which is great).
I have a repo with ~50 Commits ~342 MB in size, one specific commit has 993 MB size, 31921 files in 881 folders. [Yes, you heard right]

I am just asking whether this is slow or quick.... [I  guess slow, as I have a SSD and a HDD (the repo is on the HDD) and the HDD is not at fullspeed....]

Thanks for your answer.

PS: If you need my source, feel free to ask. The repo can be found @ http://dev-downloads.libreoffice.org/bibisect/win/
PS2: I am updating a progressbar [no difference in time, when I don't], and I use CheckoutModifier.Force

**Comment by nulltoken** [comment]
@ethomson Does your recent improvements to checkout perf (cf. https://github.com/libgit2/libgit2/pull/2866)  would help us regarding this issue?

**Comment by clns** [comment]
Any update here?

**Comment by ethomson** [comment]
Should be fixed.  Are you seeing that your checkout is slower than git.git?

**Comment by clns** [comment]
Yes, I have a medium repo (~17,094 commits, ~89408 files) and checking out a commit (with a clean workdir) takes ~30-40 secs (takes only a couple seconds from the cli). 

Also another, possibly related, slowness is with [`git_describe_workdir()`](https://github.com/libgit2/libgit2/blob/c369b37919114f4976b7a06107506e95916e5dd0/src/describe.c#L725), and I think it's because of [`git_status_list_new()`](https://github.com/libgit2/libgit2/blob/c369b37919114f4976b7a06107506e95916e5dd0/src/describe.c#L747), because [`git_describe_commit()`](https://github.com/libgit2/libgit2/blob/c369b37919114f4976b7a06107506e95916e5dd0/src/describe.c#L744) is fast, on the same HEAD commit but not considering workdir files.

However all this happens on Windows, not OS X (haven't tested on Linux) - with a clean workdir.

I'm using the `Release` configuration of [libgit2](https://github.com/libgit2/libgit2) and sadly I don't have more specific figures at the moment.

**Comment by carlosmn** [comment]
Have you measured that it's the *checkout* that takes extra time and not the status? git parallelises part of the status check, which we do not do, and which would affect the overall time even if checking out the files isn't slower than with git.

**Comment by clns** [comment]
No I haven't. However I'm inclined to believe that it is the status because, on the above mentioned repo, **checkout** still completes in under a minute, but **workdir describe** is not. Describe takes over a minute with a clean workdir, but with lots of ignored files, so I can't even use it.

**Comment by ethomson** [comment]
@clns I think this is unrelated to the initial issue report.  I suspect that you're using the latest Git for Windows?

**Comment by clns** [comment]
I think it is more related to the status than the checkout, yes. I was using git 2.6.1 in cli on Windows.

**Comment by ethomson** [comment]
In that case, this should be fixed by https://github.com/libgit2/libgit2/pull/3480

**Comment by clns** [comment]
@ethomson This looks awesome, cause right now I'm struggling with the checkout because it takes a very long time. Thanks!!! Hopefully it gets merged soon...

**Comment by nulltoken** [comment]
@clns This fix will be embedded in #1210

**Comment by carlosmn** [comment]
We've merged a whole bunch of nanosecond fixes, so I'm closing this as resolved by the release of 0.22.
